#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building execline (one of the requirements to building s6)
# Adjust these as neccessary

EXECLINE_VERSION="execline-2.1.1.0"

# You shouldn't need to change these, but you can as required

EXECLINE_FILE="$EXECLINE_VERSION.tar.gz"
EXECLINE_URL="http://skarnet.org/software/execline/$EXECLINE_FILE"

# download execline into packages
curl -o /package/$EXECLINE_FILE $EXECLINE_URL

# unzip the execline package
cd /package
tar -zxpvf $EXECLINE_FILE
rm $EXECLINE_FILE

wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
tar -xvf make-4.1.tar.gz
cd make-4.1
./configure
./build.sh
mv make ../make
cd ..
rm -rf make-4.1

# setup the configuration
cd $EXECLINE_VERSION

export CC=musl-gcc

./configure --enable-slashpackage

# install execline
../make
sudo ../make install
../make clean

rm /package/admin/execline || true
sudo ln -s /package/admin/$EXECLIN_VERSION /package/admin/execline