#!/usr/bin/env bash
set -e
set -x

# This script will automate the process of building s6
# Adjust these as neccessary

s6_VERSION="s6-2.1.3.0"

# You shouldn't need to change these, but you can as required

s6_FILE="$s6_VERSION.tar.gz"
s6_URL="http://www.skarnet.org/software/s6/$s6_FILE"

# download s6 into packages
if [ ! -e /package/$s6_FILE ]
then
    curl -o /package/$s6_FILE $s6_URL
fi

# unzip the s6 package
cd /package
tar -zxpvf $s6_FILE

cd $s6_VERSION

CC=musl-gcc ./configure --enable-slashpackage --enable-static-libc

# make s6
../make
../make install
../make clean

rm /package/admin/s6 || true
sudo ln -s /package/admin/$s6_VERSION /package/admin/s6

if [ ! -e /vagrant/dist/ ]
then
    mkdir /vagrant/dist/
fi

# gzip the files ready to go
tar -zcf /vagrant/dist/$s6_VERSION-static.tar.gz -C /package/admin/s6/command .

# also copy them across into /vagrant/ubuntu-base/root/usr/bin
if [ -e /vagrant/ubuntu-base/root/usr/bin ]
then
    rm -rf /vagrant/ubuntu-base/root/usr
fi
mkdir -p /vagrant/ubuntu-base/root/usr/bin
cp /package/admin/s6/command/* /vagrant/ubuntu-base/root/usr/bin
