#!/usr/bin/env bash

# Bind to the external (LAN) IP
BIND="$(getent hosts $HOSTNAME | awk '{print $1}')"

if [ -z "$MASTER" ]
then
	echo "Master not set!"
	exit 1
else
	next="-join=$MASTER"
fi

exec consul agent -config-dir /etc/consul.d/bootstrap $next -dc $DATACENTER;
